### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by rik-rosseel** [motion-canvas/motion-canvas#251]
When trying to initialize a motion canvas project following the quick start docs I get the following error:

```
~/Coding/motion-canvas$ npm init @motion-canvas
file:///home/rik/.npm/_npx/f9ebd6605af41bbe/node_modules/@motion-canvas/create/index.js:152
  return ua?.split(' ')[0].split('/')[0] ?? 'npm';
            ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /home/rik/Coding/motion-canvas
npm ERR! command failed
npm ERR! command sh -c create-motion-canvas

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rik/.npm/_logs/2023-02-08T14_32_23_190Z-debug-0.log
```
Not sure if this is an issue on my side so any help is appreciated!
I'm trying to get this set up on Ubuntu 22.04.1 LTS.

The created debug log:
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'init', '@motion-canvas' ]
1 info using npm@8.5.1
2 info using node@v12.22.9
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 12ms
6 timing config:load:builtin Completed in 12ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/rik/Coding/motion-canvas/.npmrc Completed in 0ms
10 timing config:load:project Completed in 11ms
11 timing config:load:file:/home/rik/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 16ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 45ms
19 timing npm:load:configload Completed in 45ms
20 timing npm:load:setTitle Completed in 1ms
21 timing config:load:flatten Completed in 3ms
22 timing npm:load:display Completed in 4ms
23 verbose logfile /home/rik/.npm/_logs/2023-02-08T14_32_23_190Z-debug-0.log
24 timing npm:load:logFile Completed in 27ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 79ms
28 http fetch GET 200 https://registry.npmjs.org/@motion-canvas%2fcreate 1074ms (cache miss)
29 timing arborist:ctor Completed in 0ms
30 timing arborist:ctor Completed in 0ms
31 timing arborist:ctor Completed in 0ms
32 timing command:init Completed in 1257ms
33 verbose stack Error: command failed
33 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
33 verbose stack     at ChildProcess.emit (events.js:314:20)
33 verbose stack     at maybeClose (internal/child_process.js:1022:16)
33 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
34 verbose cwd /home/rik/Coding/motion-canvas
35 verbose Linux 5.15.0-58-generic
36 verbose argv "/usr/bin/node" "/usr/bin/npm" "init" "@motion-canvas"
37 verbose node v12.22.9
38 verbose npm  v8.5.1
39 error code 1
40 error path /home/rik/Coding/motion-canvas
41 error command failed
42 error command sh -c create-motion-canvas
43 verbose exit 1
44 timing npm Completed in 2528ms
45 verbose code 1
46 error A complete log of this run can be found in:
46 error     /home/rik/.npm/_logs/2023-02-08T14_32_23_190Z-debug-0.log
```

**Comment by Tandashi** [comment]
Looks like you are using NodeJS `12.22.9`. Motion Canvas requires NodeJS `v16+`. Make sure to install or use a newer version.

**Comment by rik-rosseel** [comment]
Thanks!
