### ISSUE TITLE
Console Error when reusing time event.

### ISSUE THREAD

**Issue by RannyBergamotte** [motion-canvas/motion-canvas#475]
**Describe the bug**
Console error when reusing events
Animation seems to work just fine though.

**To Reproduce**
```
import {makeScene2D} from '@motion-canvas/2d/lib/scenes';
import {waitFor, waitUntil} from '@motion-canvas/core/lib/flow';
import {Circle} from '@motion-canvas/2d/lib/components';
import {createRef, useDuration} from '@motion-canvas/core/lib/utils';
import {all} from '@motion-canvas/core/lib/flow';

export default makeScene2D(function* (view) {
  // Create your animations here
  const myCircle = createRef<Circle>();

view.add(
  <Circle
    ref={myCircle}
    x={-300}
    width={240}
    height={240}
    fill="#e13238"
    opacity={0}
  />,
);


yield* all(
  myCircle().position.x(300,useDuration('cmove1') ),
  myCircle().opacity(1,useDuration('cmove1')),
); 

yield* waitUntil('event');
yield* all(
  myCircle().position.x(-300,1)
  
);

});
```

**Expected behavior**
No console errors, the animation works just fine, using only one event for two animated properties.

**Console errors**
```
name "cmove1" has already been used for another event name.
The problem occurred here:
25 |   myCircle().opacity(1,useDuration('cmove1')),
   |                        ^
26 | ); 
27 | 

at (/node_modules/.vite/deps/chunk-XNO4YMBB.js:3293:16)
at (/node_modules/.vite/deps/chunk-XNO4YMBB.js:5319:20)
at (/src/scenes/example.tsx:25:23)
at (/node_modules/.vite/deps/chunk-XNO4YMBB.js:5456:32)
at (/node_modules/.vite/deps/chunk-XNO4YMBB.js:5507:29)
at (/node_modules/.vite/deps/chunk-XNO4YMBB.js:4963:32)
at (/node_modules/.vite/deps/@motion-canvas_2d_lib_scenes.js:32:18)
at (/node_modules/.vite/deps/chunk-XNO4YMBB.js:5012:16)
at (/node_modules/.vite/deps/@motion-canvas_2d_lib_scenes.js:53:18)
at (/node_modules/.vite/deps/chunk-FFW2XNAB.js:202:33)
at (/node_modules/.vite/deps/chunk-FFW2XNAB.js:677:27)
at (/node_modules/.vite/deps/chunk-FFW2XNAB.js:712:11)
```

**Package versions (please complete the following information):**
did a git clone of the current version today, so looking at the core changelog.md 3.0.0 and ui 3.0.1?

**Additional context**
I am a complete beginner to this (really really cool and powerful btw! hats off to aarthificial and the other devs), so maybe there is a better way to do this or I am doing something wrong, but this seemed logical and the console error was throwing me off.

**Comment by aarthificial** [comment]
If you need to reuse the duration of a time event, you should store it in a variable:
```ts
const duration = useDuration('cmove1');
yield* all(
  myCircle().position.x(300, duration),
  myCircle().opacity(1, duration),
); 
```
The call to `useDuration` is used by the editor to figure out where on the timeline the event should be placed.
It's only okay in your specific example because you're running both animations at the same time - so they end up located in the same place.
