### ISSUE TITLE
The thread is not available in the current context

### ISSUE THREAD

**Issue by theoparis** [motion-canvas/motion-canvas#479]
**Describe the bug**

An error occurs when I use a custom vite project with motion canvas.

**To Reproduce**

I have simply created a vite project with `yarn add -D vite`, added the motion canvas vite plugin, and I added the css import and copied the rest of the quick start code. Do I need the preact vite plugin as well? Am i missing something else?

```ts
import "@motion-canvas/ui/dist/style.css";
import { makeProject } from "@motion-canvas/core";

import example from "./scenes/example?scene";

export default makeProject({
	scenes: [example],
});
```

```tsx
import { makeScene2D } from "@motion-canvas/2d/lib/scenes";
import { Circle } from "@motion-canvas/2d/lib/components";
import { createRef } from "@motion-canvas/core/lib/utils";
import { all } from "@motion-canvas/core/lib/flow";

export default makeScene2D(function* (view) {
	const myCircle = createRef<Circle>();

	view.add(
		<Circle ref={myCircle} x={-300} width={240} height={240} fill="#e13238" />,
	);

	yield* all(
		myCircle().position.x(300, 1).to(-300, 1),
		myCircle().fill("#e6a700", 1).to("#e13238", 1),
	);
});
```

```ts
import { defineConfig } from "vite";
import motionCanvas from "@motion-canvas/vite-plugin";

export default defineConfig({
        plugins: [motionCanvas({})],
        build: {
                rollupOptions: {
                        output: {
                                entryFileNames: "[name].js",
                        },
                },
        },
});
```

**Expected behavior**
The UI loads fine but there is a error in the console.

**Console errors**
```
main.js:49293 Error: The thread is not available in the current context.
    at useThread (useThread.ts:12:11)
    at join (join.ts:54:18)
    at join.next (<anonymous>)
    at all (all.ts:24:10)
    at all.next (<anonymous>)
    at Scene2D.runnerFactory (example.tsx:13:9)
    at Generator.next (<anonymous>)
    at Thread.next (Thread.ts:58:32)
    at threads (threads.ts:74:29)
    at threads.next (<anonymous>)
    at Scene2D.next (GeneratorScene.ts:229:32)
    at Scene2D.next (Scene2D.ts:33:18)
    at Scene2D.reset (GeneratorScene.ts:286:16)
    at Scene2D.reset (Scene2D.ts:57:18)
    at Scene2D.recalculate (GeneratorScene.ts:195:16)
    at PlaybackManager.recalculate (PlaybackManager.ts:124:21)
    at Player.prepare (Player.ts:316:29)
    at Player.run (Player.ts:357:30)
    at Player.ts:432:22
```

**Package versions (please complete the following information):**

- core: 3.0.0
- ui: 3.0.1

**Additional context**
I am using chromium `Version 110.0.5481.177 (Official Build) Arch Linux (64-bit)`.

I also get this as a warning in the JS console:
```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
```

**Comment by aarthificial** [comment]
Are you able to share a repo that has this problem?
I have trouble reproducing it.

**Comment by aarthificial** [comment]
Closing due to no response
