### ISSUE TITLE
3.3.0 breaks stuff

### ISSUE THREAD

**Issue by cyberalien** [motion-canvas/motion-canvas#545]
**Describe the bug**
After updating to 3.3.0, getting this error:

```
Failed to resolve import "@motion-canvas/2d/lib/jsx-dev-runtime" from "src/scenes/tests/code-test.tsx". Does the file exist?
9:31:42 AM [vite] Internal server error: Failed to resolve import "@motion-canvas/2d/lib/jsx-dev-runtime" from "src/scenes/tests/code-test.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: ./src/scenes/tests/code-test.tsx:45:3
  1  |  import { jsxDEV } from "@motion-canvas/2d/lib/jsx-dev-runtime";
     |                          ^
  2  |  import { makeScene2D } from "@motion-canvas/2d/lib/scenes";
  3  |  import { Node, Rect } from "@motion-canvas/2d/lib/components";
      at formatError (node_modules/vite/dist/node/chunks/dep-c167897e.js:43098:46)
      at TransformContext.error (node_modules/vite/dist/node/chunks/dep-c167897e.js:43094:19)
      at normalizeUrl (node_modules/vite/dist/node/chunks/dep-c167897e.js:41363:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (node_modules/vite/dist/node/chunks/dep-c167897e.js:41497:47)
      at async Object.transform (node_modules/vite/dist/node/chunks/dep-c167897e.js:43372:30)
      at async loadAndTransform (node_modules/vite/dist/node/chunks/dep-c167897e.js:41090:29)
```

Dependencies in package.json:
```
"dependencies": {
		"@motion-canvas/2d": "^3.3.0",
		"@motion-canvas/core": "^3.3.0"
	},
	"devDependencies": {
		"@motion-canvas/ui": "^3.3.0",
		"@motion-canvas/vite-plugin": "^3.3.0",
		"typescript": "^4.9.5",
		"vite": "^4.1.4"
	}
```

Tested on 2 installations that use different scenes, so absolutely nothing in scenes that would throw any errors, both fail with same error.

**Comment by aarthificial** [comment]
Should be fixed in [`3.3.1`](https://github.com/motion-canvas/motion-canvas/releases/tag/v3.3.1)
