### ISSUE TITLE
Cannot init on Zorin (Ubuntu)

### ISSUE THREAD

**Issue by code32123** [motion-canvas/motion-canvas#768]
**Describe the bug**
Hello! I'm trying to get this running on Zorin, based on Ubuntu, but I can't get past the init. I've never used node on this system, so everything should be completely fresh.

**To Reproduce**
A seconds old npm & nodejs setup, then the commands:
`npm init @motion-canvas@latest`
*Fails per #196*
`npm init @motion-canvas`
```
npx: installed 5 in 1.972s
/home/User/.npm/_npx/21137/lib/node_modules/@motion-canvas/create/index.js:3
import prompts from 'prompts';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
`npm install @motion-canvas/create`
```
npm WARN saveError ENOENT: no such file or directory, open '/home/flicker/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/flicker/package.json'
npm WARN flicker No description
npm WARN flicker No repository field.
npm WARN flicker No README data
npm WARN flicker No license field.

+ @motion-canvas/create@3.9.0
added 5 packages from 4 contributors and audited 5 packages in 0.274s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
`npm install @motion-canvas`
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@motion-canvas": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/flicker/.npm/_logs/2023-07-11T21_27_11_803Z-debug.log
```

**Expected behavior**
A demo project so I can start working on a new animation.

**Console errors**
<details>
  <summary>Full shell log</summary>

```
UserName@CSystemName:~$ npm init @motion-canvas@latest
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@motion-canvas": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/UserName/.npm/_logs/2023-07-11T21_13_55_343Z-debug.log
UserName@CSystemName:~$ node -v
v10.19.0
UserName@CSystemName:~$ npm init @motion-canvas@latest
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@motion-canvas": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/UserName/.npm/_logs/2023-07-11T21_14_12_085Z-debug.log
UserName@CSystemName:~$ ^C
UserName@CSystemName:~$ npm init @motion-canvas
npx: installed 5 in 1.972s
/home/UserName/.npm/_npx/21137/lib/node_modules/@motion-canvas/create/index.js:3
import prompts from 'prompts';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
UserName@CSystemName:~$ npm init @motion-canvas@latest
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@motion-canvas": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/UserName/.npm/_logs/2023-07-11T21_16_56_815Z-debug.log
UserName@CSystemName:~$ npm exec @motion-canvas/create@latest

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/UserName/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.4 /usr/share/npm

UserName@CSystemName:~$ npm init @motion-canvas@latest
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@motion-canvas": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/UserName/.npm/_logs/2023-07-11T21_18_24_829Z-debug.log
UserName@CSystemName:~$ npm install @motion-canvas/create
npm WARN saveError ENOENT: no such file or directory, open '/home/UserName/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/UserName/package.json'
npm WARN UserName No description
npm WARN UserName No repository field.
npm WARN UserName No README data
npm WARN UserName No license field.

+ @motion-canvas/create@3.9.0
added 5 packages from 4 contributors and audited 5 packages in 0.274s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

UserName@CSystemName:~$ npm install @motion-canvas
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@motion-canvas": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/UserName/.npm/_logs/2023-07-11T21_19_38_395Z-debug.log
UserName@CSystemName:~$ npm init @motion-canvas
npx: installed 5 in 1.578s
/home/UserName/.npm/_npx/21667/lib/node_modules/@motion-canvas/create/index.js:3
import prompts from 'prompts';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
</details>

**Package versions:**
Newest

**Comment by aarthificial** [comment]
The log you've attached suggests that your Node.js version is `10.19.0`:
```
UserName@CSystemName:~$ node -v
v10.19.0
```
Motion Canvas [requires at least version 16](https://motioncanvas.io/docs/quickstart#prerequisites).

If you've used apt-get to install Node.js that might be the problem.
For some reason, the default repositories on Ubuntu are stuck on version 10.
You can [take a look at these official docs](https://nodejs.org/en/download/package-manager#debian-and-ubuntu-based-linux-distributions) on how to install Node.js using a package manager on Ubuntu-based distros.
