### ISSUE TITLE
Inconsistent package versions when generating project using `npm init @motion-canvas@latest`

### ISSUE THREAD

**Issue by lsarrazi** [motion-canvas/motion-canvas#807]
**Describe the bug**
Versions of packages are not fixed in a `package-lock.json` when generating project using `npm init @motion-canvas@latest` which might lead to errors at runtime in specific conditions.

**Comment by lsarrazi** [comment]
Example:
This guy when I `npm install` :
```
    "node_modules/follow-redirects": {
      "version": "1.15.2",
      "funding": [
        {
          "type": "individual",
          "url": "https://github.com/sponsors/RubenVerborgh"
        }
      ],
      "license": "MIT",
      "engines": {
        "node": ">=4.0"
      },
      "peerDependenciesMeta": {
        "debug": {
          "optional": true
        }
      }
    },
```

But fixed at a different version on the main repo (same motion-canvas version tho):

```
"node_modules/@types/follow-redirects": {
      "version": "1.14.1",
      "resolved": "https://registry.npmjs.org/@types/follow-redirects/-/follow-redirects-1.14.1.tgz",
      "integrity": "sha512-THBEFwqsLuU/K62B5JRwab9NW97cFmL4Iy34NTMX0bMycQVzq2q7PKOkhfivIwxdpa/J72RppgC42vCHfwKJ0Q==",
      "dev": true,
      "dependencies": {
        "@types/node": "*"
      }
    },
```

**Comment by lsarrazi** [comment]
Im not quite sure of it but since im getting this error from @motion-canvas/vite-plugin :
```
index.js:68 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at node_modules/follow-redirects/index.js (index.js:68:56)
    at __require2 (chunk-HYZYPRER.js?v=cdabeb68:15:50)
    at node_modules/@motion-canvas/vite-plugin/lib/proxy-middleware.js (proxy-middleware.js:20:28)
    at __require2 (chunk-HYZYPRER.js?v=cdabeb68:15:50)
    at node_modules/@motion-canvas/vite-plugin/lib/main.js (main.js:33:28)
    at __require2 (chunk-HYZYPRER.js?v=cdabeb68:15:50)
    at node_modules/@motion-canvas/vite-plugin/lib/index.js (index.js:20:32)
    at __require2 (chunk-HYZYPRER.js?v=cdabeb68:15:50)
    at index.js:22:43
```

When trying to define a configuration:

```ts

export default makeProject({
  scenes: [example],
  plugins: [
    motionCanvas({
    }),
  ],
});
```

I suspect the version of `follow-redirects` not be enforced leading to this bug.

**Comment by lsarrazi** [comment]
Complete confusion on my side, I used vite-plugin inside project.ts which is is not designed for this at all (should be in vite.config.ts)
Closing this issue right now
